[project]
name = "dense-kg-vector-db"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "annoy>=1.17.3",
    "cmake==4.4.2",
    "datasets>=4.8.4",
    "dotenv>=0.9.9",
    "jupyter>=1.1.1",
    "neo4j>=6.2.0",
    "ninja>=1.13.0",
    "numpy==2.3.3",
    "oxrdflib>=0.5.0",
    "pandas>=3.0.1",
    "pillow>=12.1.1",
    "psutil>=7.2.2",
    "pywikibot>=11.2.0",
    "rdflib>=7.6.0",
    "requests-oauthlib>=2.0.0",
    "seaborn>=0.13.2",
    "sentence-transformers>=5.3.0",
    "simplejson>=3.20.2",
    "swig>=4.4.1",
    "tikzplotlib-patched>=0.10.1.post13",
    "tqdm>=4.67.3",
]

