[project]
name = "dense-kg-vector-db"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "annoy>=1.17.3",
    "cmake==3.31.10",
    "jupyter>=1.1.1",
    "ninja>=1.13.0",
    "numpy==2.3.3",
    "oxrdflib>=0.5.0",
    "pandas>=3.0.1",
    "rdflib>=7.6.0",
    "sentence-transformers>=5.3.0",
    "swig>=4.4.1",
    "tqdm>=4.67.3",
]

